name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: npm install
    
    - name: Webpack build
      run: npx webpack --mode production
    
    - name: Type check
      run: npm run type-check
    
    - name: Verify build artifacts
      run: |
        test -d dist || exit 1
        test -f dist/bundle.js || exit 1
        test -f dist/index.html || exit 1
        echo "✓ Build artifacts created successfully"
    
    - name: Verify Python launcher syntax
      run: python -m py_compile launcher.py
    
    - name: Build Electron app (on main branch only)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx electron-builder --linux --publish never
      env:
        ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
        ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
    
    - name: Upload build artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: electron-distributables
        path: release/**/*
        retention-days: 7
